chore(hooks): change message text on pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,9 +1,9 @@
 #! /bin/bash
 
-echo 'Generating docs...'
+echo '[pre-commit] Generating Helm docs...'
 
 helm-docs 2> /dev/null
 
-[[ $(git diff charts/*/README.md) ]] && (echo 'ERROR: documentation updated!' && exit 1)
+[[ $(git diff charts/*/README.md) ]] && (echo 'ERROR: Helm documentation updated!' && exit 1)
 
 exit 0
